# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  - trigger: ":mail"
    replace: "mail2soumikdas@gmail.com"

  - trigger: ":roll"
    replace: "220383444"

  - trigger: ":id"
    replace: "sd366@student.london.ac.uk"

  - trigger: ":work"
    replace: ":soumik.das@tripsygames.com"

  - trigger: ":link"
    replace: "https://www.linkedin.com/in/soumik-das-profile/"

  - trigger: ":git"
    replace: "https://github.com/FalconEthics"

  - trigger: ":insta"
    replace: "https://www.instagram.com/itz.raaj.das/"

  - trigger: ":bio"
    replace: "A CSE Student from University of London | Founder of STEMHUB | React-Native Developer at Wisedeck Technologies | and a guy u would love to chill with🥂"

  - trigger: ":twi"
    replace: "https://twitter.com/Mr_Soumik_Das"

  - trigger: ":web"
    replace: "https://mrsoumikdas.com/"

  - trigger: ":md"
    replace: "https://medium.com/@stemhub"

  - trigger: ":bd"
    replace: "22/05/2003"

  - trigger: ":add"
    replace: "Santinagar, W/No. 3"
    
  - trigger: ":no"
    replace: "+91 9854027242"
    
  - trigger: ":nm"
    replace: "Soumik Das"

  - trigger: ":cover"
    replace: "Dear HR Team, 
\n
\nAs a passionate and skilled professional, I am excited to apply for the available role within your organization. With expertise in frontend web development, I bring a unique perspective and a commitment to delivering exceptional results.
\n
\nMy skills and experience are complemented by my strong work ethic, attention to detail, and ability to work collaboratively with others. Although I may have less experience compared to other applicants, I am confident in my ability to make a meaningful contribution to your team. I am passionate about what I do.
\n
\nI would be honored to have the opportunity to discuss how my skills and background align with the role, and I look forward to hearing from you.
\n
\nBest regards,
\n
\nSoumik Das
\nsoumik-das.com"
    
  - trigger: ":clg"
    replace: "BSc Computer Science from University of London"
   
  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!

  # But matches can also be dynamic:

  # Print the current date
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Print the output of a shell command
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

  # And much more! For more information, visit the docs: https://espanso.org/docs/
